/**
 * Count-locked Rekka component contract. New project component NIDs must be
 * implemented and added here; strict boot then fails instead of silently
 * accepting data that the runtime has never reviewed.
 */
export const REKKA_ITEM_COMPONENTS = new Set([
  'advance', 'advance_target_restrict', 'all_allies_except_self_aoe',
  'allow_same_target', 'ally_blast_aoe', 'ally_equation_blast_aoe',
  'alternate_damage_formula', 'alternate_resist_formula', 'attack_after_combat',
  'blast_aoe', 'brave', 'c_uses', 'can_unlock', 'cannot_be_countered', 'crit',
  'custom_triangle_multiplier', 'damage', 'draw_back', 'draw_back_target_restrict',
  'effective_damage', 'empty_tile_target_restrict', 'enemy_blast_aoe',
  'enemy_line_aoe', 'equation_blast_aoe', 'equation_heal',
  'equippable_accessory', 'eval_special_range', 'eval_target_restrict_2',
  'event_after_combat_even_miss', 'event_after_combat_on_hit', 'event_on_hit',
  'exp', 'gba_steal', 'global_range', 'gold_cost', 'heal', 'hit', 'hp_cost',
  'ignore_weapon_advantage', 'item_tags', 'level_exp', 'lifelink', 'locked',
  'magic', 'magic_at_range', 'map_cast_sfx', 'map_hit_add_blend', 'map_hit_sfx',
  'max_equation_range', 'max_range', 'menu_after_combat', 'min_range',
  'multi_target', 'no_ai', 'no_attack_after_move', 'no_double',
  'no_map_hp_display', 'permanent_stat_change', 'pivot', 'pivot_target_restrict',
  'prf_class', 'prf_unit', 'promote', 'reaver', 'refresh', 'repair', 'restore',
  'restore_specific', 'self_status_on_hit', 'sequence_item', 'shove',
  'shove_on_end_combat', 'shove_target_restrict', 'siege_weapon',
  'smart_blast_aoe', 'spell', 'stat_change', 'status_on_equip', 'status_on_hit',
  'status_on_hold', 'steal', 'store_unit', 'swap', 'swap_on_end_combat',
  'target_ally', 'target_enemy', 'target_tile', 'target_unit', 'trace', 'trade',
  'transform', 'traversable_tile_target_restrict', 'unload_unit', 'unlock_staff',
  'usable', 'usable_in_base', 'uses', 'uses_options', 'value', 'warning',
  'weapon', 'weapon_rank', 'weapon_type', 'weight', 'wexp',
]);

export const REKKA_SKILL_COMPONENTS = new Set([
  'TrueMiracle', 'ability', 'additional_accessories', 'all_brave',
  'allowed_weapons', 'alternate_critical_multiplier_formula', 'armsthrift',
  'attack_pre_proc', 'attack_proc', 'aura', 'aura_range', 'aura_target', 'avoid',
  'cannot_double', 'cannot_use_items', 'cannot_use_items_except_armor',
  'cannot_use_magic_items', 'canter', 'canto', 'canto_plus', 'change_ai',
  'change_buy_price', 'charges_per_turn', 'class_skill', 'combat_art',
  'combat_artist', 'combat_condition', 'condition', 'crit', 'crit_avoid',
  'damage', 'damage_multiplier', 'death_tether',
  'decreasing_sight_range_bonus', 'defense_pre_proc', 'defense_speed',
  'desperation', 'display_skill_icon_in_combat', 'distant_counter', 'disvantage',
  'drain_charge', 'dynamic_accuracy', 'dynamic_avoid', 'dynamic_crit_accuracy',
  'dynamic_damage', 'dynamic_damage_multiplier', 'dynamic_resist', 'empower_heal',
  'end_time', 'endstep_damage', 'enemy_exp_multiplier', 'enemy_oversplash',
  'eval_galeforce', 'event_after_combat', 'event_after_combat_when_hit',
  'event_after_crit', 'event_after_hit', 'event_after_initiated_combat',
  'event_after_strike', 'event_before_combat', 'event_on_remove',
  'event_on_upkeep', 'event_when_hit', 'exp_multiplier', 'gain_skill_after_attack',
  'gain_skill_after_combat', 'gain_skill_after_kill',
  'gain_skill_after_take_damage', 'gain_skill_after_take_miss', 'galeforce',
  'give_status_after_combat', 'givebacker', 'global', 'grey_if_inactive',
  'grounded', 'growth_change', 'guaranteed_crit', 'has_tags', 'hidden',
  'hidden_if_inactive', 'hit', 'ignore_alliances', 'ignore_damage',
  'ignore_terrain', 'immune_status', 'item_override', 'lifelink', 'live_to_serve',
  'locktouch', 'lost_on_end_chapter', 'lost_on_end_combat2', 'lost_on_endstep',
  'lost_on_kill', 'lost_on_upkeep', 'miracle', 'modify_ai_priority',
  'modify_maximum_range', 'movement_type', 'multi_skill', 'negate', 'negative',
  'nine_lives_event', 'no_attack_after_move', 'pass', 'post_combat_splash',
  'post_combat_splash_aoe', 'powerstaff', 'proc_rate', 'reflect_status',
  'regeneration', 'resist', 'resist_multiplier', 'second_wind',
  'sight_range_bonus', 'skill_before_combat', 'stack', 'stat_change',
  'stat_change_expression', 'stat_multiplier', 'time',
  'true_miracle_event_after_combat', 'unit_flickering_tint', 'unit_tint',
  'unselectable', 'upkeep_event', 'upkeep_stat_change', 'vantage',
  'wexp_multiplier', 'wexp_usable_skill', 'witch_warp_expression',
]);
